"""
Project Euler - Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def solve(limit=4000000):
    """
    Calculate the sum of even Fibonacci numbers not exceeding the limit.
    
    Args:
        limit: The maximum value for Fibonacci numbers to consider
        
    Returns:
        The sum of all even Fibonacci numbers below limit
    """
    a, b = 1, 2
    total = 0
    
    while a <= limit:
        if a % 2 == 0:
            total += a
        a, b = b, a + b
    
    return total


def solve_optimized(limit=4000000):
    """
    Optimized solution using the fact that every third Fibonacci number is even.
    
    If we look at the sequence: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    Even numbers appear at positions: 2, 8, 34, ... (every third position)
    
    We can generate only even Fibonacci numbers directly:
    If E(n) is the nth even Fibonacci number, then E(n+1) = 4*E(n) + E(n-1)
    """
    a, b = 2, 8  # First two even Fibonacci numbers
    total = a
    
    while b <= limit:
        total += b
        a, b = b, 4 * b + a
    
    return total


if __name__ == "__main__":
    result = solve()
    print(f"Solution (basic): {result}")
    
    result_optimized = solve_optimized()
    print(f"Solution (optimized): {result_optimized}")
    
    # Verify both methods give the same result
    assert result == result_optimized, "Solutions don't match!"
    print(f"\nAnswer: {result}")
